# Generated by Django 2.2.2 on 2019-11-02 10:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadType', models.CharField(default='not_set', max_length=70)),
                ('uploadKey', models.CharField(default='not_set', max_length=70)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location='C:\\Users\\Haris\\Desktop\\gravity\\static'), upload_to='common/uploads')),
            ],
        ),
    ]
