# Generated by Django 2.2.2 on 2019-11-03 09:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=344)),
                ('message', models.TextField()),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location='C:\\Users\\Haris\\Desktop\\gravity\\static'), upload_to='uploads/userdata'),
        ),
    ]
