# Generated by Django 2.2.2 on 2019-11-03 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
